"""timm 1.0.29 EVA-family configs (generated from timm.models.eva registrations).

Each entry: Eva constructor overrides (non-default values) and the default eval config.
"""

EVA_CFGS = {
    "eva02_base_patch14_224": (
        {
            "patch_size": 14,
            "qkv_fused": False,
            "mlp_ratio": 2.6666666666666665,
            "swiglu_mlp": True,
            "scale_mlp": True,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (16, 16),
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.48145466, 0.4578275, 0.40821073),
            "std": (0.26862954, 0.26130258, 0.27577711),
        },
    ),
    "eva02_base_patch14_448": (
        {
            "img_size": 448,
            "patch_size": 14,
            "qkv_fused": False,
            "mlp_ratio": 2.6666666666666665,
            "swiglu_mlp": True,
            "scale_mlp": True,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (16, 16),
        },
        {
            "input_size": (3, 448, 448),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.48145466, 0.4578275, 0.40821073),
            "std": (0.26862954, 0.26130258, 0.27577711),
            "crop_mode": "squash",
        },
    ),
    "eva02_base_patch16_clip_224": (
        {
            "qkv_fused": False,
            "mlp_ratio": 2.6666666666666665,
            "swiglu_mlp": True,
            "scale_mlp": True,
            "scale_attn_inner": True,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (16, 16),
            "global_pool": "token",
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.48145466, 0.4578275, 0.40821073),
            "std": (0.26862954, 0.26130258, 0.27577711),
        },
    ),
    "eva02_enormous_patch14_clip_224": (
        {
            "patch_size": 14,
            "embed_dim": 1792,
            "depth": 64,
            "num_heads": 16,
            "mlp_ratio": 8.571428571428571,
            "use_post_norm": True,
            "global_pool": "token",
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.48145466, 0.4578275, 0.40821073),
            "std": (0.26862954, 0.26130258, 0.27577711),
        },
    ),
    "eva02_large_patch14_224": (
        {
            "patch_size": 14,
            "embed_dim": 1024,
            "depth": 24,
            "num_heads": 16,
            "mlp_ratio": 2.6666666666666665,
            "qkv_fused": False,
            "swiglu_mlp": True,
            "scale_mlp": True,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (16, 16),
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.48145466, 0.4578275, 0.40821073),
            "std": (0.26862954, 0.26130258, 0.27577711),
        },
    ),
    "eva02_large_patch14_448": (
        {
            "img_size": 448,
            "patch_size": 14,
            "embed_dim": 1024,
            "depth": 24,
            "num_heads": 16,
            "mlp_ratio": 2.6666666666666665,
            "qkv_fused": False,
            "swiglu_mlp": True,
            "scale_mlp": True,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (16, 16),
        },
        {
            "input_size": (3, 448, 448),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.48145466, 0.4578275, 0.40821073),
            "std": (0.26862954, 0.26130258, 0.27577711),
            "crop_mode": "squash",
        },
    ),
    "eva02_large_patch14_clip_224": (
        {
            "patch_size": 14,
            "embed_dim": 1024,
            "depth": 24,
            "num_heads": 16,
            "mlp_ratio": 2.6666666666666665,
            "qkv_fused": False,
            "swiglu_mlp": True,
            "scale_mlp": True,
            "scale_attn_inner": True,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (16, 16),
            "global_pool": "token",
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.48145466, 0.4578275, 0.40821073),
            "std": (0.26862954, 0.26130258, 0.27577711),
        },
    ),
    "eva02_large_patch14_clip_336": (
        {
            "img_size": 336,
            "patch_size": 14,
            "embed_dim": 1024,
            "depth": 24,
            "num_heads": 16,
            "mlp_ratio": 2.6666666666666665,
            "qkv_fused": False,
            "swiglu_mlp": True,
            "scale_mlp": True,
            "scale_attn_inner": True,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (16, 16),
            "global_pool": "token",
        },
        {
            "input_size": (3, 336, 336),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.48145466, 0.4578275, 0.40821073),
            "std": (0.26862954, 0.26130258, 0.27577711),
        },
    ),
    "eva02_small_patch14_224": (
        {
            "patch_size": 14,
            "embed_dim": 384,
            "num_heads": 6,
            "mlp_ratio": 2.6666666666666665,
            "swiglu_mlp": True,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (16, 16),
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.48145466, 0.4578275, 0.40821073),
            "std": (0.26862954, 0.26130258, 0.27577711),
        },
    ),
    "eva02_small_patch14_336": (
        {
            "img_size": 336,
            "patch_size": 14,
            "embed_dim": 384,
            "num_heads": 6,
            "mlp_ratio": 2.6666666666666665,
            "swiglu_mlp": True,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (16, 16),
        },
        {
            "input_size": (3, 336, 336),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.48145466, 0.4578275, 0.40821073),
            "std": (0.26862954, 0.26130258, 0.27577711),
        },
    ),
    "eva02_tiny_patch14_224": (
        {
            "patch_size": 14,
            "embed_dim": 192,
            "num_heads": 3,
            "mlp_ratio": 2.6666666666666665,
            "swiglu_mlp": True,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (16, 16),
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.48145466, 0.4578275, 0.40821073),
            "std": (0.26862954, 0.26130258, 0.27577711),
        },
    ),
    "eva02_tiny_patch14_336": (
        {
            "img_size": 336,
            "patch_size": 14,
            "embed_dim": 192,
            "num_heads": 3,
            "mlp_ratio": 2.6666666666666665,
            "swiglu_mlp": True,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (16, 16),
        },
        {
            "input_size": (3, 336, 336),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.48145466, 0.4578275, 0.40821073),
            "std": (0.26862954, 0.26130258, 0.27577711),
        },
    ),
    "eva_giant_patch14_224": (
        {
            "patch_size": 14,
            "embed_dim": 1408,
            "depth": 40,
            "num_heads": 16,
            "mlp_ratio": 4.363636363636363,
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.48145466, 0.4578275, 0.40821073),
            "std": (0.26862954, 0.26130258, 0.27577711),
        },
    ),
    "eva_giant_patch14_336": (
        {
            "patch_size": 14,
            "embed_dim": 1408,
            "depth": 40,
            "num_heads": 16,
            "mlp_ratio": 4.363636363636363,
            "img_size": 336,
        },
        {
            "input_size": (3, 336, 336),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.48145466, 0.4578275, 0.40821073),
            "std": (0.26862954, 0.26130258, 0.27577711),
            "crop_mode": "squash",
        },
    ),
    "eva_giant_patch14_560": (
        {
            "patch_size": 14,
            "embed_dim": 1408,
            "depth": 40,
            "num_heads": 16,
            "mlp_ratio": 4.363636363636363,
            "img_size": 560,
        },
        {
            "input_size": (3, 560, 560),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
            "crop_mode": "squash",
        },
    ),
    "eva_giant_patch14_clip_224": (
        {
            "patch_size": 14,
            "embed_dim": 1408,
            "depth": 40,
            "num_heads": 16,
            "mlp_ratio": 4.363636363636363,
            "global_pool": "token",
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.48145466, 0.4578275, 0.40821073),
            "std": (0.26862954, 0.26130258, 0.27577711),
        },
    ),
    "vit_7b_patch16_dinov3": (
        {
            "dynamic_img_size": True,
            "embed_dim": 4096,
            "depth": 40,
            "num_heads": 32,
            "qkv_bias": False,
            "mlp_ratio": 2,
            "init_values": 1e-05,
            "rope_type": "dinov3",
            "rope_temperature": 100,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "rope_rotate_half": True,
            "swiglu_mlp": True,
            "swiglu_align_to": 64,
            "num_reg_tokens": 4,
            "use_fc_norm": False,
            "norm_eps": 1e-05,
            "img_size": 256,
        },
        {
            "input_size": (3, 256, 256),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_base_patch16_dinov3": (
        {
            "dynamic_img_size": True,
            "qkv_bias": False,
            "init_values": 1e-05,
            "rope_type": "dinov3",
            "rope_temperature": 100,
            "rope_rotate_half": True,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "num_reg_tokens": 4,
            "use_fc_norm": False,
            "norm_eps": 1e-05,
            "img_size": 256,
        },
        {
            "input_size": (3, 256, 256),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_base_patch16_dinov3_qkvb": (
        {
            "dynamic_img_size": True,
            "init_values": 1e-05,
            "rope_type": "dinov3",
            "rope_temperature": 100,
            "rope_rotate_half": True,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "num_reg_tokens": 4,
            "use_fc_norm": False,
            "norm_eps": 1e-05,
            "img_size": 256,
        },
        {
            "input_size": (3, 256, 256),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_base_patch16_lingbot": (
        {
            "dynamic_img_size": True,
            "global_pool": "token",
            "init_values": 1e-05,
            "rope_type": "dinov3",
            "rope_temperature": 100,
            "rope_rotate_half": True,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "num_reg_tokens": 4,
            "use_fc_norm": False,
            "norm_eps": 1e-05,
            "img_size": 512,
        },
        {
            "input_size": (3, 512, 512),
            "crop_pct": 1.0,
            "interpolation": "bilinear",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
            "crop_mode": "squash",
        },
    ),
    "vit_base_patch16_rope_224": (
        {
            "attn_type": "rope",
            "use_fc_norm": False,
            "init_values": 1e-05,
            "global_pool": "token",
            "use_abs_pos_emb": False,
            "use_rot_pos_emb": True,
            "rope_grid_indexing": "xy",
            "rope_temperature": 100.0,
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_base_patch16_rope_ape_224": (
        {
            "attn_type": "rope",
            "init_values": 1e-05,
            "global_pool": "token",
            "no_embed_class": True,
            "use_rot_pos_emb": True,
            "rope_grid_indexing": "xy",
            "rope_temperature": 100.0,
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_base_patch16_rope_mixed_224": (
        {
            "attn_type": "rope",
            "init_values": 1e-05,
            "global_pool": "token",
            "use_abs_pos_emb": False,
            "use_rot_pos_emb": True,
            "rope_grid_indexing": "xy",
            "rope_temperature": 10.0,
            "rope_type": "mixed",
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_base_patch16_rope_mixed_ape_224": (
        {
            "attn_type": "rope",
            "init_values": 1e-05,
            "global_pool": "token",
            "no_embed_class": True,
            "use_rot_pos_emb": True,
            "rope_grid_indexing": "xy",
            "rope_temperature": 10.0,
            "rope_type": "mixed",
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_base_patch16_rope_reg1_gap_256": (
        {
            "img_size": 256,
            "init_values": 1e-05,
            "class_token": False,
            "num_reg_tokens": 1,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "ref_feat_shape": (16, 16),
        },
        {
            "input_size": (3, 256, 256),
            "crop_pct": 0.95,
            "interpolation": "bicubic",
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
        },
    ),
    "vit_betwixt_patch16_rope_reg4_gap_256": (
        {
            "img_size": 256,
            "embed_dim": 640,
            "num_heads": 10,
            "init_values": 1e-05,
            "class_token": False,
            "num_reg_tokens": 4,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "ref_feat_shape": (16, 16),
        },
        {
            "input_size": (3, 256, 256),
            "crop_pct": 0.95,
            "interpolation": "bicubic",
            "mean": (0.48145466, 0.4578275, 0.40821073),
            "std": (0.26862954, 0.26130258, 0.27577711),
        },
    ),
    "vit_giant_patch16_lingbot": (
        {
            "dynamic_img_size": True,
            "embed_dim": 1536,
            "depth": 40,
            "num_heads": 24,
            "qkv_bias": False,
            "global_pool": "token",
            "mlp_ratio": 2.6666666666666665,
            "init_values": 1e-05,
            "rope_type": "dinov3",
            "rope_temperature": 100,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "rope_rotate_half": True,
            "swiglu_mlp": True,
            "swiglu_align_to": 8,
            "num_reg_tokens": 4,
            "use_fc_norm": False,
            "norm_eps": 1e-05,
            "img_size": 512,
        },
        {
            "input_size": (3, 512, 512),
            "crop_pct": 1.0,
            "interpolation": "bilinear",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
            "crop_mode": "squash",
        },
    ),
    "vit_huge_plus_patch16_dinov3": (
        {
            "dynamic_img_size": True,
            "embed_dim": 1280,
            "depth": 32,
            "num_heads": 20,
            "qkv_bias": False,
            "init_values": 1e-05,
            "rope_type": "dinov3",
            "rope_temperature": 100,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "rope_rotate_half": True,
            "swiglu_mlp": True,
            "swiglu_align_to": 8,
            "num_reg_tokens": 4,
            "use_fc_norm": False,
            "norm_eps": 1e-05,
            "img_size": 256,
        },
        {
            "input_size": (3, 256, 256),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_huge_plus_patch16_dinov3_qkvb": (
        {
            "dynamic_img_size": True,
            "embed_dim": 1280,
            "depth": 32,
            "num_heads": 20,
            "init_values": 1e-05,
            "rope_type": "dinov3",
            "rope_temperature": 100,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "rope_rotate_half": True,
            "swiglu_mlp": True,
            "swiglu_align_to": 8,
            "num_reg_tokens": 4,
            "use_fc_norm": False,
            "norm_eps": 1e-05,
            "img_size": 256,
        },
        {
            "input_size": (3, 256, 256),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_large_patch16_dinov3": (
        {
            "dynamic_img_size": True,
            "embed_dim": 1024,
            "depth": 24,
            "num_heads": 16,
            "qkv_bias": False,
            "init_values": 1e-05,
            "rope_type": "dinov3",
            "rope_temperature": 100,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "rope_rotate_half": True,
            "num_reg_tokens": 4,
            "use_fc_norm": False,
            "norm_eps": 1e-05,
            "img_size": 256,
        },
        {
            "input_size": (3, 256, 256),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_large_patch16_dinov3_qkvb": (
        {
            "dynamic_img_size": True,
            "embed_dim": 1024,
            "depth": 24,
            "num_heads": 16,
            "init_values": 1e-05,
            "rope_type": "dinov3",
            "rope_temperature": 100,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "rope_rotate_half": True,
            "num_reg_tokens": 4,
            "use_fc_norm": False,
            "norm_eps": 1e-05,
            "img_size": 256,
        },
        {
            "input_size": (3, 256, 256),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_large_patch16_lingbot": (
        {
            "dynamic_img_size": True,
            "embed_dim": 1024,
            "depth": 24,
            "num_heads": 16,
            "global_pool": "token",
            "init_values": 1e-05,
            "rope_type": "dinov3",
            "rope_temperature": 100,
            "rope_rotate_half": True,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "num_reg_tokens": 4,
            "use_fc_norm": False,
            "norm_eps": 1e-05,
            "img_size": 512,
        },
        {
            "input_size": (3, 512, 512),
            "crop_pct": 1.0,
            "interpolation": "bilinear",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
            "crop_mode": "squash",
        },
    ),
    "vit_large_patch16_rope_224": (
        {
            "embed_dim": 1024,
            "depth": 24,
            "num_heads": 16,
            "attn_type": "rope",
            "init_values": 1e-05,
            "global_pool": "token",
            "use_abs_pos_emb": False,
            "use_rot_pos_emb": True,
            "rope_grid_indexing": "xy",
            "rope_temperature": 100.0,
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_large_patch16_rope_ape_224": (
        {
            "embed_dim": 1024,
            "depth": 24,
            "num_heads": 16,
            "attn_type": "rope",
            "init_values": 1e-05,
            "global_pool": "token",
            "no_embed_class": True,
            "use_rot_pos_emb": True,
            "rope_grid_indexing": "xy",
            "rope_temperature": 100.0,
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_large_patch16_rope_mixed_224": (
        {
            "embed_dim": 1024,
            "depth": 24,
            "num_heads": 16,
            "attn_type": "rope",
            "init_values": 1e-05,
            "global_pool": "token",
            "use_abs_pos_emb": False,
            "use_rot_pos_emb": True,
            "rope_grid_indexing": "xy",
            "rope_temperature": 10.0,
            "rope_type": "mixed",
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_large_patch16_rope_mixed_ape_224": (
        {
            "embed_dim": 1024,
            "depth": 24,
            "num_heads": 16,
            "attn_type": "rope",
            "init_values": 1e-05,
            "global_pool": "token",
            "no_embed_class": True,
            "use_rot_pos_emb": True,
            "rope_grid_indexing": "xy",
            "rope_temperature": 10.0,
            "rope_type": "mixed",
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_medium_patch16_rope_reg1_gap_256": (
        {
            "img_size": 256,
            "embed_dim": 512,
            "num_heads": 8,
            "init_values": 1e-05,
            "class_token": False,
            "num_reg_tokens": 1,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "ref_feat_shape": (16, 16),
        },
        {
            "input_size": (3, 256, 256),
            "crop_pct": 0.95,
            "interpolation": "bicubic",
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
        },
    ),
    "vit_mediumd_patch16_rope_reg1_gap_256": (
        {
            "img_size": 256,
            "embed_dim": 512,
            "depth": 20,
            "num_heads": 8,
            "qkv_bias": False,
            "init_values": 1e-05,
            "class_token": False,
            "num_reg_tokens": 1,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "ref_feat_shape": (16, 16),
        },
        {
            "input_size": (3, 256, 256),
            "crop_pct": 0.95,
            "interpolation": "bicubic",
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
        },
    ),
    "vit_pe_core_base_patch16_224": (
        {
            "global_pool": "map",
            "attn_type": "rope",
            "use_pre_transformer_norm": True,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (14, 14),
            "rope_grid_offset": 1.0,
            "rope_grid_indexing": "xy",
            "attn_pool_num_heads": 8,
            "attn_pool_mlp_ratio": 4.0,
            "norm_eps": 1e-05,
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
        },
    ),
    "vit_pe_core_gigantic_patch14_448": (
        {
            "patch_size": 14,
            "embed_dim": 1536,
            "depth": 50,
            "num_heads": 16,
            "mlp_ratio": 5.833333333333333,
            "global_pool": "map",
            "attn_type": "rope",
            "class_token": False,
            "use_pre_transformer_norm": True,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (32, 32),
            "rope_grid_indexing": "xy",
            "attn_pool_num_heads": 8,
            "attn_pool_mlp_ratio": 4.0,
            "norm_eps": 1e-05,
            "img_size": 448,
        },
        {
            "input_size": (3, 448, 448),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
        },
    ),
    "vit_pe_core_large_patch14_336": (
        {
            "patch_size": 14,
            "embed_dim": 1024,
            "depth": 24,
            "num_heads": 16,
            "global_pool": "map",
            "attn_type": "rope",
            "use_pre_transformer_norm": True,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (24, 24),
            "rope_grid_offset": 1.0,
            "rope_grid_indexing": "xy",
            "attn_pool_num_heads": 8,
            "attn_pool_mlp_ratio": 4.0,
            "norm_eps": 1e-05,
            "img_size": 336,
        },
        {
            "input_size": (3, 336, 336),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
        },
    ),
    "vit_pe_core_small_patch16_384": (
        {
            "embed_dim": 384,
            "num_heads": 6,
            "global_pool": "map",
            "attn_type": "rope",
            "use_pre_transformer_norm": True,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (24, 24),
            "rope_grid_offset": 1.0,
            "rope_grid_indexing": "xy",
            "attn_pool_num_heads": 8,
            "attn_pool_mlp_ratio": 4.0,
            "norm_eps": 1e-05,
            "img_size": 384,
        },
        {
            "input_size": (3, 384, 384),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
        },
    ),
    "vit_pe_core_tiny_patch16_384": (
        {
            "embed_dim": 192,
            "num_heads": 3,
            "global_pool": "map",
            "attn_type": "rope",
            "use_pre_transformer_norm": True,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (24, 24),
            "rope_grid_offset": 1.0,
            "rope_grid_indexing": "xy",
            "attn_pool_num_heads": 8,
            "attn_pool_mlp_ratio": 4.0,
            "norm_eps": 1e-05,
            "img_size": 384,
        },
        {
            "input_size": (3, 384, 384),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
        },
    ),
    "vit_pe_lang_gigantic_patch14_448": (
        {
            "patch_size": 14,
            "embed_dim": 1536,
            "depth": 47,
            "num_heads": 16,
            "mlp_ratio": 5.833333333333333,
            "attn_type": "rope",
            "class_token": False,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (32, 32),
            "rope_grid_indexing": "xy",
            "use_pre_transformer_norm": True,
            "use_post_transformer_norm": False,
            "use_fc_norm": False,
            "init_values": 0.1,
            "norm_eps": 1e-05,
            "img_size": 448,
        },
        {
            "input_size": (3, 448, 448),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
        },
    ),
    "vit_pe_lang_large_patch14_448": (
        {
            "patch_size": 14,
            "embed_dim": 1024,
            "depth": 23,
            "num_heads": 16,
            "attn_type": "rope",
            "use_rot_pos_emb": True,
            "ref_feat_shape": (32, 32),
            "rope_grid_offset": 1.0,
            "rope_grid_indexing": "xy",
            "use_pre_transformer_norm": True,
            "use_post_transformer_norm": False,
            "use_fc_norm": False,
            "init_values": 0.1,
            "norm_eps": 1e-05,
            "img_size": 448,
        },
        {
            "input_size": (3, 448, 448),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
        },
    ),
    "vit_pe_spatial_base_patch16_512": (
        {
            "attn_type": "rope",
            "use_pre_transformer_norm": True,
            "use_post_transformer_norm": False,
            "use_fc_norm": False,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (32, 32),
            "rope_grid_offset": 1.0,
            "rope_grid_indexing": "xy",
            "norm_eps": 1e-05,
            "img_size": 512,
        },
        {
            "input_size": (3, 512, 512),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
        },
    ),
    "vit_pe_spatial_gigantic_patch14_448": (
        {
            "patch_size": 14,
            "embed_dim": 1536,
            "depth": 50,
            "num_heads": 16,
            "mlp_ratio": 5.833333333333333,
            "attn_type": "rope",
            "class_token": False,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (32, 32),
            "rope_grid_indexing": "xy",
            "use_pre_transformer_norm": True,
            "use_post_transformer_norm": False,
            "use_fc_norm": False,
            "init_values": 0.1,
            "norm_eps": 1e-05,
            "img_size": 448,
        },
        {
            "input_size": (3, 448, 448),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
        },
    ),
    "vit_pe_spatial_large_patch14_448": (
        {
            "patch_size": 14,
            "embed_dim": 1024,
            "depth": 24,
            "num_heads": 16,
            "attn_type": "rope",
            "use_pre_transformer_norm": True,
            "use_post_transformer_norm": False,
            "use_fc_norm": False,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (32, 32),
            "rope_grid_offset": 1.0,
            "rope_grid_indexing": "xy",
            "norm_eps": 1e-05,
            "img_size": 448,
        },
        {
            "input_size": (3, 448, 448),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
        },
    ),
    "vit_pe_spatial_small_patch16_512": (
        {
            "embed_dim": 384,
            "num_heads": 6,
            "attn_type": "rope",
            "use_pre_transformer_norm": True,
            "use_post_transformer_norm": False,
            "use_fc_norm": False,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (32, 32),
            "rope_grid_offset": 1.0,
            "rope_grid_indexing": "xy",
            "norm_eps": 1e-05,
            "img_size": 512,
        },
        {
            "input_size": (3, 512, 512),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
        },
    ),
    "vit_pe_spatial_tiny_patch16_512": (
        {
            "embed_dim": 192,
            "num_heads": 3,
            "attn_type": "rope",
            "use_pre_transformer_norm": True,
            "use_post_transformer_norm": False,
            "use_fc_norm": False,
            "use_rot_pos_emb": True,
            "ref_feat_shape": (32, 32),
            "rope_grid_offset": 1.0,
            "rope_grid_indexing": "xy",
            "norm_eps": 1e-05,
            "img_size": 512,
        },
        {
            "input_size": (3, 512, 512),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
        },
    ),
    "vit_small_patch16_dinov3": (
        {
            "dynamic_img_size": True,
            "embed_dim": 384,
            "num_heads": 6,
            "qkv_bias": False,
            "init_values": 1e-05,
            "rope_type": "dinov3",
            "rope_temperature": 100,
            "rope_rotate_half": True,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "num_reg_tokens": 4,
            "use_fc_norm": False,
            "norm_eps": 1e-05,
            "img_size": 256,
        },
        {
            "input_size": (3, 256, 256),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_small_patch16_dinov3_qkvb": (
        {
            "dynamic_img_size": True,
            "embed_dim": 384,
            "num_heads": 6,
            "init_values": 1e-05,
            "rope_type": "dinov3",
            "rope_temperature": 100,
            "rope_rotate_half": True,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "num_reg_tokens": 4,
            "use_fc_norm": False,
            "norm_eps": 1e-05,
            "img_size": 256,
        },
        {
            "input_size": (3, 256, 256),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_small_patch16_lingbot": (
        {
            "dynamic_img_size": True,
            "embed_dim": 384,
            "num_heads": 6,
            "global_pool": "token",
            "init_values": 1e-05,
            "rope_type": "dinov3",
            "rope_temperature": 100,
            "rope_rotate_half": True,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "num_reg_tokens": 4,
            "use_fc_norm": False,
            "norm_eps": 1e-05,
            "img_size": 512,
        },
        {
            "input_size": (3, 512, 512),
            "crop_pct": 1.0,
            "interpolation": "bilinear",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
            "crop_mode": "squash",
        },
    ),
    "vit_small_patch16_rope_224": (
        {
            "embed_dim": 384,
            "num_heads": 6,
            "attn_type": "rope",
            "init_values": 1e-05,
            "global_pool": "token",
            "use_abs_pos_emb": False,
            "use_rot_pos_emb": True,
            "rope_grid_indexing": "xy",
            "rope_temperature": 100.0,
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_small_patch16_rope_ape_224": (
        {
            "embed_dim": 384,
            "num_heads": 6,
            "attn_type": "rope",
            "init_values": 1e-05,
            "global_pool": "token",
            "no_embed_class": True,
            "use_rot_pos_emb": True,
            "rope_grid_indexing": "xy",
            "rope_temperature": 100.0,
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_small_patch16_rope_mixed_224": (
        {
            "embed_dim": 384,
            "num_heads": 6,
            "attn_type": "rope",
            "init_values": 1e-05,
            "global_pool": "token",
            "use_abs_pos_emb": False,
            "use_rot_pos_emb": True,
            "rope_grid_indexing": "xy",
            "rope_temperature": 10.0,
            "rope_type": "mixed",
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_small_patch16_rope_mixed_ape_224": (
        {
            "embed_dim": 384,
            "num_heads": 6,
            "attn_type": "rope",
            "init_values": 1e-05,
            "global_pool": "token",
            "no_embed_class": True,
            "use_rot_pos_emb": True,
            "rope_grid_indexing": "xy",
            "rope_temperature": 10.0,
            "rope_type": "mixed",
            "img_size": 224,
        },
        {
            "input_size": (3, 224, 224),
            "crop_pct": 0.9,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_small_plus_patch16_dinov3": (
        {
            "dynamic_img_size": True,
            "embed_dim": 384,
            "num_heads": 6,
            "qkv_bias": False,
            "init_values": 1e-05,
            "rope_type": "dinov3",
            "rope_temperature": 100,
            "rope_rotate_half": True,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "swiglu_mlp": True,
            "swiglu_align_to": 8,
            "num_reg_tokens": 4,
            "use_fc_norm": False,
            "norm_eps": 1e-05,
            "img_size": 256,
        },
        {
            "input_size": (3, 256, 256),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_small_plus_patch16_dinov3_qkvb": (
        {
            "dynamic_img_size": True,
            "embed_dim": 384,
            "num_heads": 6,
            "init_values": 1e-05,
            "rope_type": "dinov3",
            "rope_temperature": 100,
            "rope_rotate_half": True,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "swiglu_mlp": True,
            "swiglu_align_to": 8,
            "num_reg_tokens": 4,
            "use_fc_norm": False,
            "norm_eps": 1e-05,
            "img_size": 256,
        },
        {
            "input_size": (3, 256, 256),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "vit_tiny_patch16_dinov3_qkvb": (
        {
            "dynamic_img_size": True,
            "embed_dim": 192,
            "num_heads": 3,
            "init_values": 1e-05,
            "rope_type": "dinov3",
            "rope_temperature": 100,
            "rope_rotate_half": True,
            "use_rot_pos_emb": True,
            "use_abs_pos_emb": False,
            "num_reg_tokens": 4,
            "use_fc_norm": False,
            "norm_eps": 1e-05,
            "img_size": 256,
        },
        {
            "input_size": (3, 256, 256),
            "crop_pct": 1.0,
            "interpolation": "bicubic",
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
}
