"""timm 1.0.29 MaxxViT model configs (generated from timm.models.maxxvit.model_cfgs).

Each entry lists only fields that differ from the dataclass defaults in _maxxvit.py:
base fields, then "conv" and "transformer" overrides, then the default eval config.
"""

CONV_DEFAULTS = {
    "block_type": "mbconv",
    "expand_ratio": 4.0,
    "expand_output": True,
    "kernel_size": 3,
    "group_size": 1,
    "pre_norm_act": False,
    "output_bias": True,
    "stride_mode": "dw",
    "pool_type": "avg2",
    "downsample_pool_type": "avg2",
    "padding": "",
    "attn_early": False,
    "attn_layer": "se",
    "attn_act_layer": "silu",
    "attn_ratio": 0.25,
    "init_values": 1e-06,
    "act_layer": "gelu",
    "norm_layer": "batchnorm2d",
    "norm_layer_cl": "",
    "norm_eps": 1e-05,
}
TRANSFORMER_DEFAULTS = {
    "dim_head": 32,
    "head_first": True,
    "expand_ratio": 4.0,
    "expand_first": True,
    "shortcut_bias": True,
    "attn_bias": True,
    "attn_drop": 0.0,
    "proj_drop": 0.0,
    "pool_type": "avg2",
    "rel_pos_type": "bias",
    "rel_pos_dim": 512,
    "partition_ratio": 32,
    "window_size": None,
    "grid_size": None,
    "no_block_attn": False,
    "use_nchw_attn": False,
    "init_values": None,
    "act_layer": "gelu",
    "norm_layer": "layernorm2d",
    "norm_layer_cl": "layernorm",
    "norm_eps": 1e-06,
}

MAXXVIT_CFGS = {
    "coatnet_0_224": (
        {
            "head_hidden_size": 768,
            "embed_dim": (96, 192, 384, 768),
            "depths": (2, 3, 5, 2),
            "block_type": ("C", "C", "T", "T"),
        },
        {},
        {},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_0_rw_224": (
        {
            "depths": (2, 3, 7, 2),
            "stem_width": (32, 64),
            "embed_dim": (96, 192, 384, 768),
            "block_type": ("C", "C", "T", "T"),
        },
        {
            "expand_output": False,
            "pre_norm_act": True,
            "output_bias": False,
            "stride_mode": "pool",
            "attn_early": True,
            "attn_act_layer": "relu",
            "act_layer": "silu",
        },
        {"expand_first": False, "shortcut_bias": False},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_1_224": (
        {
            "depths": (2, 6, 14, 2),
            "head_hidden_size": 768,
            "embed_dim": (96, 192, 384, 768),
            "block_type": ("C", "C", "T", "T"),
        },
        {},
        {},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_1_rw_224": (
        {
            "depths": (2, 6, 14, 2),
            "stem_width": (32, 64),
            "embed_dim": (96, 192, 384, 768),
            "block_type": ("C", "C", "T", "T"),
        },
        {
            "expand_output": False,
            "pre_norm_act": True,
            "output_bias": False,
            "attn_early": True,
            "attn_act_layer": "relu",
            "act_layer": "silu",
        },
        {"expand_first": False, "shortcut_bias": False},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_2_224": (
        {
            "embed_dim": (128, 256, 512, 1024),
            "depths": (2, 6, 14, 2),
            "stem_width": 128,
            "head_hidden_size": 1024,
            "block_type": ("C", "C", "T", "T"),
        },
        {},
        {},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_2_rw_224": (
        {
            "embed_dim": (128, 256, 512, 1024),
            "depths": (2, 6, 14, 2),
            "stem_width": (64, 128),
            "block_type": ("C", "C", "T", "T"),
        },
        {"expand_output": False, "pre_norm_act": True, "output_bias": False, "act_layer": "silu"},
        {"expand_first": False},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_3_224": (
        {
            "embed_dim": (192, 384, 768, 1536),
            "depths": (2, 6, 14, 2),
            "stem_width": 192,
            "head_hidden_size": 1536,
            "block_type": ("C", "C", "T", "T"),
        },
        {},
        {},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_3_rw_224": (
        {
            "embed_dim": (192, 384, 768, 1536),
            "depths": (2, 6, 14, 2),
            "stem_width": (96, 192),
            "block_type": ("C", "C", "T", "T"),
        },
        {"expand_output": False, "pre_norm_act": True, "output_bias": False, "act_layer": "silu"},
        {"expand_first": False, "init_values": 1e-06},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_4_224": (
        {
            "embed_dim": (192, 384, 768, 1536),
            "depths": (2, 12, 28, 2),
            "stem_width": 192,
            "head_hidden_size": 1536,
            "block_type": ("C", "C", "T", "T"),
        },
        {},
        {},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_5_224": (
        {
            "embed_dim": (256, 512, 1280, 2048),
            "depths": (2, 12, 28, 2),
            "stem_width": 192,
            "head_hidden_size": 2048,
            "block_type": ("C", "C", "T", "T"),
        },
        {},
        {},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_bn_0_rw_224": (
        {
            "depths": (2, 3, 7, 2),
            "stem_width": (32, 64),
            "embed_dim": (96, 192, 384, 768),
            "block_type": ("C", "C", "T", "T"),
        },
        {
            "expand_output": False,
            "pre_norm_act": True,
            "output_bias": False,
            "attn_early": True,
            "attn_act_layer": "relu",
            "act_layer": "silu",
        },
        {"expand_first": False, "shortcut_bias": False, "norm_layer": "batchnorm2d"},
        {
            "img_size": 224,
            "crop_pct": 0.95,
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "coatnet_nano_cc_224": (
        {
            "embed_dim": (64, 128, 256, 512),
            "depths": (3, 4, 6, 3),
            "block_type": ("C", "C", ("C", "T"), ("C", "T")),
            "stem_width": (32, 64),
        },
        {
            "expand_output": False,
            "pre_norm_act": True,
            "output_bias": False,
            "stride_mode": "pool",
            "attn_act_layer": "relu",
            "act_layer": "silu",
        },
        {"expand_first": False},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_nano_rw_224": (
        {
            "embed_dim": (64, 128, 256, 512),
            "depths": (3, 4, 6, 3),
            "stem_width": (32, 64),
            "block_type": ("C", "C", "T", "T"),
        },
        {"expand_output": False, "stride_mode": "pool", "act_layer": "silu"},
        {"expand_first": False},
        {"img_size": 224, "crop_pct": 0.9, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_pico_rw_224": (
        {
            "embed_dim": (64, 128, 256, 512),
            "stem_width": (32, 64),
            "depths": (2, 3, 5, 2),
            "block_type": ("C", "C", "T", "T"),
        },
        {"expand_output": False, "act_layer": "silu"},
        {"expand_first": False},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_rmlp_0_rw_224": (
        {
            "depths": (2, 3, 7, 2),
            "stem_width": (32, 64),
            "embed_dim": (96, 192, 384, 768),
            "block_type": ("C", "C", "T", "T"),
        },
        {
            "expand_output": False,
            "pre_norm_act": True,
            "output_bias": False,
            "attn_act_layer": "relu",
            "act_layer": "silu",
        },
        {"expand_first": False, "rel_pos_type": "mlp"},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_rmlp_1_rw2_224": (
        {
            "depths": (2, 6, 14, 2),
            "stem_width": (32, 64),
            "embed_dim": (96, 192, 384, 768),
            "block_type": ("C", "C", "T", "T"),
        },
        {
            "expand_output": False,
            "pre_norm_act": True,
            "output_bias": False,
            "attn_act_layer": "relu",
            "act_layer": "silu",
        },
        {"expand_first": False, "rel_pos_type": "mlp"},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_rmlp_1_rw_224": (
        {
            "depths": (2, 6, 14, 2),
            "stem_width": (32, 64),
            "embed_dim": (96, 192, 384, 768),
            "block_type": ("C", "C", "T", "T"),
        },
        {
            "expand_output": False,
            "pre_norm_act": True,
            "output_bias": False,
            "stride_mode": "pool",
            "pool_type": "max",
            "attn_early": True,
            "attn_act_layer": "relu",
            "act_layer": "silu",
        },
        {
            "expand_first": False,
            "shortcut_bias": False,
            "pool_type": "max",
            "rel_pos_type": "mlp",
            "rel_pos_dim": 384,
        },
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_rmlp_2_rw_224": (
        {
            "embed_dim": (128, 256, 512, 1024),
            "depths": (2, 6, 14, 2),
            "stem_width": (64, 128),
            "block_type": ("C", "C", "T", "T"),
        },
        {"expand_output": False, "pre_norm_act": True, "output_bias": False, "act_layer": "silu"},
        {"expand_first": False, "rel_pos_type": "mlp", "init_values": 1e-06},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_rmlp_2_rw_384": (
        {
            "embed_dim": (128, 256, 512, 1024),
            "depths": (2, 6, 14, 2),
            "stem_width": (64, 128),
            "block_type": ("C", "C", "T", "T"),
        },
        {"expand_output": False, "pre_norm_act": True, "output_bias": False, "act_layer": "silu"},
        {"expand_first": False, "rel_pos_type": "mlp", "init_values": 1e-06},
        {
            "img_size": 384,
            "crop_pct": 1.0,
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
            "crop_mode": "squash",
        },
    ),
    "coatnet_rmlp_3_rw_224": (
        {
            "embed_dim": (192, 384, 768, 1536),
            "depths": (2, 6, 14, 2),
            "stem_width": (96, 192),
            "block_type": ("C", "C", "T", "T"),
        },
        {"expand_output": False, "pre_norm_act": True, "output_bias": False, "act_layer": "silu"},
        {"expand_first": False, "rel_pos_type": "mlp", "init_values": 1e-06},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnet_rmlp_nano_rw_224": (
        {
            "embed_dim": (64, 128, 256, 512),
            "depths": (3, 4, 6, 3),
            "stem_width": (32, 64),
            "block_type": ("C", "C", "T", "T"),
        },
        {"expand_output": False, "act_layer": "silu"},
        {"expand_first": False, "rel_pos_type": "mlp", "rel_pos_dim": 384},
        {"img_size": 224, "crop_pct": 0.9, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "coatnext_nano_rw_224": (
        {
            "embed_dim": (64, 128, 256, 512),
            "depths": (3, 4, 6, 3),
            "stem_width": (32, 64),
            "block_type": ("C", "C", "T", "T"),
        },
        {
            "block_type": "convnext",
            "expand_output": False,
            "init_values": 1e-05,
            "norm_layer": "layernorm2d",
            "norm_layer_cl": "layernorm",
            "norm_eps": 1e-06,
        },
        {"expand_first": False},
        {"img_size": 224, "crop_pct": 0.9, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxvit_base_tf_224": (
        {
            "depths": (2, 6, 14, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_bias": True,
            "head_hidden_size": 768,
            "embed_dim": (96, 192, 384, 768),
        },
        {"padding": "same", "act_layer": "gelu_tanh", "norm_eps": 0.001},
        {
            "head_first": False,
            "rel_pos_type": "bias_tf",
            "act_layer": "gelu_tanh",
            "norm_eps": 1e-05,
        },
        {
            "img_size": 224,
            "crop_pct": 0.95,
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "maxvit_base_tf_384": (
        {
            "depths": (2, 6, 14, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_bias": True,
            "head_hidden_size": 768,
            "embed_dim": (96, 192, 384, 768),
        },
        {"padding": "same", "act_layer": "gelu_tanh", "norm_eps": 0.001},
        {
            "head_first": False,
            "rel_pos_type": "bias_tf",
            "act_layer": "gelu_tanh",
            "norm_eps": 1e-05,
        },
        {
            "img_size": 384,
            "crop_pct": 1.0,
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
            "crop_mode": "squash",
        },
    ),
    "maxvit_base_tf_512": (
        {
            "depths": (2, 6, 14, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_bias": True,
            "head_hidden_size": 768,
            "embed_dim": (96, 192, 384, 768),
        },
        {"padding": "same", "act_layer": "gelu_tanh", "norm_eps": 0.001},
        {
            "head_first": False,
            "rel_pos_type": "bias_tf",
            "act_layer": "gelu_tanh",
            "norm_eps": 1e-05,
        },
        {
            "img_size": 512,
            "crop_pct": 1.0,
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
            "crop_mode": "squash",
        },
    ),
    "maxvit_large_tf_224": (
        {
            "embed_dim": (128, 256, 512, 1024),
            "depths": (2, 6, 14, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": 128,
            "stem_bias": True,
            "head_hidden_size": 1024,
        },
        {"padding": "same", "act_layer": "gelu_tanh", "norm_eps": 0.001},
        {
            "head_first": False,
            "rel_pos_type": "bias_tf",
            "act_layer": "gelu_tanh",
            "norm_eps": 1e-05,
        },
        {
            "img_size": 224,
            "crop_pct": 0.95,
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "maxvit_large_tf_384": (
        {
            "embed_dim": (128, 256, 512, 1024),
            "depths": (2, 6, 14, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": 128,
            "stem_bias": True,
            "head_hidden_size": 1024,
        },
        {"padding": "same", "act_layer": "gelu_tanh", "norm_eps": 0.001},
        {
            "head_first": False,
            "rel_pos_type": "bias_tf",
            "act_layer": "gelu_tanh",
            "norm_eps": 1e-05,
        },
        {
            "img_size": 384,
            "crop_pct": 1.0,
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
            "crop_mode": "squash",
        },
    ),
    "maxvit_large_tf_512": (
        {
            "embed_dim": (128, 256, 512, 1024),
            "depths": (2, 6, 14, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": 128,
            "stem_bias": True,
            "head_hidden_size": 1024,
        },
        {"padding": "same", "act_layer": "gelu_tanh", "norm_eps": 0.001},
        {
            "head_first": False,
            "rel_pos_type": "bias_tf",
            "act_layer": "gelu_tanh",
            "norm_eps": 1e-05,
        },
        {
            "img_size": 512,
            "crop_pct": 1.0,
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
            "crop_mode": "squash",
        },
    ),
    "maxvit_nano_rw_256": (
        {
            "embed_dim": (64, 128, 256, 512),
            "depths": (1, 2, 3, 1),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (32, 64),
        },
        {"expand_output": False, "output_bias": False, "attn_ratio": 0.0625, "act_layer": "silu"},
        {"expand_first": False},
        {"img_size": 256, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxvit_pico_rw_256": (
        {
            "embed_dim": (32, 64, 128, 256),
            "depths": (2, 2, 5, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (24, 32),
        },
        {"expand_output": False, "output_bias": False, "attn_ratio": 0.0625, "act_layer": "silu"},
        {"expand_first": False},
        {"img_size": 256, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxvit_rmlp_base_rw_224": (
        {
            "depths": (2, 6, 14, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (32, 64),
            "head_hidden_size": 768,
            "embed_dim": (96, 192, 384, 768),
        },
        {"expand_output": False, "output_bias": False, "attn_ratio": 0.0625, "act_layer": "silu"},
        {"expand_first": False, "rel_pos_type": "mlp"},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxvit_rmlp_base_rw_384": (
        {
            "depths": (2, 6, 14, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (32, 64),
            "head_hidden_size": 768,
            "embed_dim": (96, 192, 384, 768),
        },
        {"expand_output": False, "output_bias": False, "attn_ratio": 0.0625, "act_layer": "silu"},
        {"expand_first": False, "rel_pos_type": "mlp"},
        {
            "img_size": 384,
            "crop_pct": 1.0,
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
            "crop_mode": "squash",
        },
    ),
    "maxvit_rmlp_nano_rw_256": (
        {
            "embed_dim": (64, 128, 256, 512),
            "depths": (1, 2, 3, 1),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (32, 64),
        },
        {"expand_output": False, "output_bias": False, "attn_ratio": 0.0625, "act_layer": "silu"},
        {"expand_first": False, "rel_pos_type": "mlp"},
        {"img_size": 256, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxvit_rmlp_pico_rw_256": (
        {
            "embed_dim": (32, 64, 128, 256),
            "depths": (2, 2, 5, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (24, 32),
        },
        {"expand_output": False, "output_bias": False, "attn_ratio": 0.0625, "act_layer": "silu"},
        {"expand_first": False, "rel_pos_type": "mlp"},
        {"img_size": 256, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxvit_rmlp_small_rw_224": (
        {
            "depths": (2, 2, 5, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (32, 64),
            "embed_dim": (96, 192, 384, 768),
        },
        {"expand_output": False, "output_bias": False, "attn_ratio": 0.0625, "act_layer": "silu"},
        {"expand_first": False, "rel_pos_type": "mlp", "init_values": 1e-06},
        {"img_size": 224, "crop_pct": 0.9, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxvit_rmlp_small_rw_256": (
        {
            "depths": (2, 2, 5, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (32, 64),
            "embed_dim": (96, 192, 384, 768),
        },
        {"expand_output": False, "output_bias": False, "attn_ratio": 0.0625, "act_layer": "silu"},
        {"expand_first": False, "rel_pos_type": "mlp", "init_values": 1e-06},
        {"img_size": 256, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxvit_rmlp_tiny_rw_256": (
        {
            "embed_dim": (64, 128, 256, 512),
            "depths": (2, 2, 5, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (32, 64),
        },
        {"expand_output": False, "output_bias": False, "attn_ratio": 0.0625, "act_layer": "silu"},
        {"expand_first": False, "rel_pos_type": "mlp"},
        {"img_size": 256, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxvit_small_tf_224": (
        {
            "depths": (2, 2, 5, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_bias": True,
            "head_hidden_size": 768,
            "embed_dim": (96, 192, 384, 768),
        },
        {"padding": "same", "act_layer": "gelu_tanh", "norm_eps": 0.001},
        {
            "head_first": False,
            "rel_pos_type": "bias_tf",
            "act_layer": "gelu_tanh",
            "norm_eps": 1e-05,
        },
        {
            "img_size": 224,
            "crop_pct": 0.95,
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "maxvit_small_tf_384": (
        {
            "depths": (2, 2, 5, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_bias": True,
            "head_hidden_size": 768,
            "embed_dim": (96, 192, 384, 768),
        },
        {"padding": "same", "act_layer": "gelu_tanh", "norm_eps": 0.001},
        {
            "head_first": False,
            "rel_pos_type": "bias_tf",
            "act_layer": "gelu_tanh",
            "norm_eps": 1e-05,
        },
        {
            "img_size": 384,
            "crop_pct": 1.0,
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
            "crop_mode": "squash",
        },
    ),
    "maxvit_small_tf_512": (
        {
            "depths": (2, 2, 5, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_bias": True,
            "head_hidden_size": 768,
            "embed_dim": (96, 192, 384, 768),
        },
        {"padding": "same", "act_layer": "gelu_tanh", "norm_eps": 0.001},
        {
            "head_first": False,
            "rel_pos_type": "bias_tf",
            "act_layer": "gelu_tanh",
            "norm_eps": 1e-05,
        },
        {
            "img_size": 512,
            "crop_pct": 1.0,
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
            "crop_mode": "squash",
        },
    ),
    "maxvit_tiny_pm_256": (
        {
            "embed_dim": (64, 128, 256, 512),
            "depths": (2, 2, 5, 2),
            "block_type": ("PM", "PM", "PM", "PM"),
            "stem_width": (32, 64),
        },
        {"expand_output": False, "output_bias": False, "attn_ratio": 0.0625, "act_layer": "silu"},
        {"expand_first": False},
        {"img_size": 256, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxvit_tiny_rw_224": (
        {
            "embed_dim": (64, 128, 256, 512),
            "depths": (2, 2, 5, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (32, 64),
        },
        {"expand_output": False, "output_bias": False, "attn_ratio": 0.0625, "act_layer": "silu"},
        {"expand_first": False},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxvit_tiny_rw_256": (
        {
            "embed_dim": (64, 128, 256, 512),
            "depths": (2, 2, 5, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (32, 64),
        },
        {"expand_output": False, "output_bias": False, "attn_ratio": 0.0625, "act_layer": "silu"},
        {"expand_first": False},
        {"img_size": 256, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxvit_tiny_tf_224": (
        {
            "embed_dim": (64, 128, 256, 512),
            "depths": (2, 2, 5, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_bias": True,
            "head_hidden_size": 512,
        },
        {"padding": "same", "act_layer": "gelu_tanh", "norm_eps": 0.001},
        {
            "head_first": False,
            "rel_pos_type": "bias_tf",
            "act_layer": "gelu_tanh",
            "norm_eps": 1e-05,
        },
        {
            "img_size": 224,
            "crop_pct": 0.95,
            "mean": (0.485, 0.456, 0.406),
            "std": (0.229, 0.224, 0.225),
        },
    ),
    "maxvit_tiny_tf_384": (
        {
            "embed_dim": (64, 128, 256, 512),
            "depths": (2, 2, 5, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_bias": True,
            "head_hidden_size": 512,
        },
        {"padding": "same", "act_layer": "gelu_tanh", "norm_eps": 0.001},
        {
            "head_first": False,
            "rel_pos_type": "bias_tf",
            "act_layer": "gelu_tanh",
            "norm_eps": 1e-05,
        },
        {
            "img_size": 384,
            "crop_pct": 1.0,
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
            "crop_mode": "squash",
        },
    ),
    "maxvit_tiny_tf_512": (
        {
            "embed_dim": (64, 128, 256, 512),
            "depths": (2, 2, 5, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_bias": True,
            "head_hidden_size": 512,
        },
        {"padding": "same", "act_layer": "gelu_tanh", "norm_eps": 0.001},
        {
            "head_first": False,
            "rel_pos_type": "bias_tf",
            "act_layer": "gelu_tanh",
            "norm_eps": 1e-05,
        },
        {
            "img_size": 512,
            "crop_pct": 1.0,
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
            "crop_mode": "squash",
        },
    ),
    "maxvit_xlarge_tf_224": (
        {
            "embed_dim": (192, 384, 768, 1536),
            "depths": (2, 6, 14, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": 192,
            "stem_bias": True,
            "head_hidden_size": 1536,
        },
        {"padding": "same", "act_layer": "gelu_tanh", "norm_eps": 0.001},
        {
            "head_first": False,
            "rel_pos_type": "bias_tf",
            "act_layer": "gelu_tanh",
            "norm_eps": 1e-05,
        },
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxvit_xlarge_tf_384": (
        {
            "embed_dim": (192, 384, 768, 1536),
            "depths": (2, 6, 14, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": 192,
            "stem_bias": True,
            "head_hidden_size": 1536,
        },
        {"padding": "same", "act_layer": "gelu_tanh", "norm_eps": 0.001},
        {
            "head_first": False,
            "rel_pos_type": "bias_tf",
            "act_layer": "gelu_tanh",
            "norm_eps": 1e-05,
        },
        {
            "img_size": 384,
            "crop_pct": 1.0,
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
            "crop_mode": "squash",
        },
    ),
    "maxvit_xlarge_tf_512": (
        {
            "embed_dim": (192, 384, 768, 1536),
            "depths": (2, 6, 14, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": 192,
            "stem_bias": True,
            "head_hidden_size": 1536,
        },
        {"padding": "same", "act_layer": "gelu_tanh", "norm_eps": 0.001},
        {
            "head_first": False,
            "rel_pos_type": "bias_tf",
            "act_layer": "gelu_tanh",
            "norm_eps": 1e-05,
        },
        {
            "img_size": 512,
            "crop_pct": 1.0,
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
            "crop_mode": "squash",
        },
    ),
    "maxxvit_rmlp_nano_rw_256": (
        {
            "embed_dim": (64, 128, 256, 512),
            "depths": (1, 2, 3, 1),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (32, 64),
        },
        {
            "block_type": "convnext",
            "expand_output": False,
            "norm_layer": "layernorm2d",
            "norm_layer_cl": "layernorm",
            "norm_eps": 1e-06,
        },
        {"expand_first": False, "rel_pos_type": "mlp", "init_values": 1e-06},
        {"img_size": 256, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxxvit_rmlp_small_rw_256": (
        {
            "depths": (2, 2, 5, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (48, 96),
            "embed_dim": (96, 192, 384, 768),
        },
        {
            "block_type": "convnext",
            "expand_output": False,
            "norm_layer": "layernorm2d",
            "norm_layer_cl": "layernorm",
            "norm_eps": 1e-06,
        },
        {"expand_first": False, "rel_pos_type": "mlp", "init_values": 1e-06},
        {"img_size": 256, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxxvit_rmlp_tiny_rw_256": (
        {
            "embed_dim": (64, 128, 256, 512),
            "depths": (2, 2, 5, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (32, 64),
        },
        {
            "block_type": "convnext",
            "expand_output": False,
            "norm_layer": "layernorm2d",
            "norm_layer_cl": "layernorm",
            "norm_eps": 1e-06,
        },
        {"expand_first": False, "rel_pos_type": "mlp", "init_values": 1e-06},
        {"img_size": 256, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxxvitv2_nano_rw_256": (
        {
            "depths": (1, 2, 3, 1),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (48, 96),
            "embed_dim": (96, 192, 384, 768),
        },
        {
            "block_type": "convnext",
            "expand_output": False,
            "norm_layer": "layernorm2d",
            "norm_layer_cl": "layernorm",
            "norm_eps": 1e-06,
        },
        {"expand_first": False, "no_block_attn": True, "init_values": 1e-06},
        {"img_size": 256, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxxvitv2_rmlp_base_rw_224": (
        {
            "embed_dim": (128, 256, 512, 1024),
            "depths": (2, 6, 12, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (64, 128),
        },
        {
            "block_type": "convnext",
            "expand_output": False,
            "norm_layer": "layernorm2d",
            "norm_layer_cl": "layernorm",
            "norm_eps": 1e-06,
        },
        {"expand_first": False, "rel_pos_type": "mlp", "no_block_attn": True, "init_values": 1e-06},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
    "maxxvitv2_rmlp_base_rw_384": (
        {
            "embed_dim": (128, 256, 512, 1024),
            "depths": (2, 6, 12, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (64, 128),
        },
        {
            "block_type": "convnext",
            "expand_output": False,
            "norm_layer": "layernorm2d",
            "norm_layer_cl": "layernorm",
            "norm_eps": 1e-06,
        },
        {"expand_first": False, "rel_pos_type": "mlp", "no_block_attn": True, "init_values": 1e-06},
        {
            "img_size": 384,
            "crop_pct": 1.0,
            "mean": (0.5, 0.5, 0.5),
            "std": (0.5, 0.5, 0.5),
            "crop_mode": "squash",
        },
    ),
    "maxxvitv2_rmlp_large_rw_224": (
        {
            "embed_dim": (160, 320, 640, 1280),
            "depths": (2, 6, 16, 2),
            "block_type": ("M", "M", "M", "M"),
            "stem_width": (80, 160),
            "head_hidden_size": 1280,
        },
        {
            "block_type": "convnext",
            "expand_output": False,
            "norm_layer": "layernorm2d",
            "norm_layer_cl": "layernorm",
            "norm_eps": 1e-06,
        },
        {"expand_first": False, "rel_pos_type": "mlp", "no_block_attn": True, "init_values": 1e-06},
        {"img_size": 224, "crop_pct": 0.95, "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5)},
    ),
}
